### ISSUE TITLE
Using command name as default label

### ISSUE THREAD

**Issue by ghost** [jerrypnz/major-mode-hydra.el#10]
Thanks for making this tool, I use it all the time!

I often want to add a quick hydra with `pretty-hydra-define`, and I'd love to have the default label for each key be the name of the command that it runs, instead of being blank. Perhaps it could even have a default but customizable transformation of the name, such as stripping the name of the major mode off the front. 

I'd love to hear your thoughts!

**Comment by jerrypnz** [comment]
@apnewberry Sorry for the late response. For some reason I didn't receive notification for this issue. That's definitely a reasonable suggestion. I didn't implement it as it got a bit complex and I personally always assign labels to the hydra heads. I'll give it another try hopefully in the next few days. Finally got a chance to get back to this project.

Also I'm really glad that you find it useful and thanks for your suggestion.

**Comment by jerrypnz** [comment]
@apnewberry Apparently it's already supported. I was looking at the tests  and realised that it's already there: https://github.com/jerrypnz/major-mode-hydra.el/blob/master/test/major-mode-hydra-test.el#L37 It's been too long and I've totally forgot about it 😂 

I also just tested it and can confirm it works, e.g:

```elisp
(major-mode-hydra-bind clojure-mode "Connect"
      ("Q" cider-quit)
```

**Comment by jerrypnz** [comment]
> Perhaps it could even have a default but customizable transformation of the name, such as stripping the name of the major mode off the front.

This is an interesting idea. I'm actually working on customisation options #11 and might give it a try.

**Comment by ghost** [comment]
Thanks, I hadn't tried it with `major-mode-hydra-bind`. The function I'm most interested in is `pretty-hydra-define`, which as far as I can tell doesn't do it. For example this display is empty:

```elisp
(pretty-hydra-define my-tmp-hydra (:hint nil)
  ("label" (("C-c a" jump-to-register))))
```

**Comment by jerrypnz** [comment]
@apnewberry sorry for taking so long to get back to it but this issue has been fixed and is available on `develop` branch.

**Comment by jerrypnz** [comment]
Actually merged it to master. Should be available on Melpa soon.
