### ISSUE TITLE
Custom column docs

### ISSUE THREAD

**Issue by dustinlacewell** [jerrypnz/major-mode-hydra.el#13]
It would be great if we could use the `major-mode-hydra-bind` or alternative macro to create columns which have pre-made docstrings. I would like to use major-mode-hydra to replicate this Hydra:

    (defhydra hydra-org (:hint nil :color red)
      "
       shift      header    level    ends    narrow

         K          p         k       a        o       [r] rifle        [SPC] cycle
         ↑          ↑         ↑       ↑        ↑       [v] avy           [t]  tidy mode: %(org-tidy-p)
    h  ←   →  l                                        [s] siblings      [L]  links
         ↓          ↓         ↓       ↓        ↓       [d] children
         J          n         j       e        i       [f] parents           level
                                                                     [ 1   2   3   4   5 ]
    "
      ("<f19>" (funcall hera-default-hydra) nil :color blue)
      ;; shift
      ("h" org-promote-subtree)
      ("l" org-demote-subtree)
      ("K" org-move-subtree-up)
      ("J" org-move-subtree-down)
      ;; header
      ("p" org-backward-heading-same-level)
      ("n" org-forward-heading-same-level)
      ;; ends
      ("a" hydra-org-goto-first-sibling)
      ("e" hydra-org-goto-last-sibling)
      ;; level
      ("j" hydra-org-child-level)
      ("k" hydra-org-parent-level)
      ;; narrow
      ("o" nn-widen)
      ("i" nn-narrow)

      ("SPC" org-cycle)
      ("t" org-tidy)
      ("L" org-toggle-link-display)

      ("r" (lambda () (interactive)
             (helm-org-rifle-current-buffer)
             (call-interactively 'org-cycle)
             (call-interactively 'org-cycle)))
      ("v" avy-org-goto-heading-timer)
      ("s" avy-org-same-level)
      ("d" avy-org-child-level)
      ("f" avy-org-parent-level)
      ("S" (lambda () (interactive) (helm-org-in-buffer-headings) (org-cycle) (org-cycle)))

      ("1" (avy-org-goto-level 1))
      ("2" (avy-org-goto-level 2))
      ("3" (avy-org-goto-level 3))
      ("4" (avy-org-goto-level 4))
      ("5" (avy-org-goto-level 5)))

**Comment by jerrypnz** [comment]
I designed this package in such a way that it dynamically recompiles the hydra one there is a change to its heads, but I guess some time it'd be useful to fully customize the hydra.

Maybe a new macro can be introduced, something like:

```elisp
(major-mode-hydra-set org-mode hydra-org)
```

Before I get a chance to implement it, you can actually do this now by manually add the hydra to `org-mode major-mode-hydra--body-cache`:

```elisp
(setf (alist-get 'org-mode major-mode-hydra--body-cache) hydra-org/body)
```

**Comment by jerrypnz** [comment]
Apart from the above hacky solution, you can also use `defhydra` directly as long as the name follows the same convention `major-mode-hydras/<mode>`, e.g. 

```
(defhydra major-mode-hydras/org-mode (:hint nil :color red)
  "
   shift      header    level    ends    narrow

     K          p         k       a        o       [r] rifle        [SPC] cycle
     ↑          ↑         ↑       ↑        ↑       [v] avy           [t]  tidy mode:  %(org-tidy-p)
h  ←   →  l                                        [s] siblings      [L]  links
     ↓          ↓         ↓       ↓        ↓       [d] children
     J          n         j       e        i       [f] parents           level
                                                                 [ 1   2   3   4   5 ]
"
  ("<f19>" (funcall hera-default-hydra) nil :color blue)
  ;; shift
  ("h" org-promote-subtree)
  ("l" org-demote-subtree)
  ("K" org-move-subtree-up)
  ("J" org-move-subtree-down)
  ;; header
  ("p" org-backward-heading-same-level)
  ("n" org-forward-heading-same-level)
  ;; ends
  ("a" hydra-org-goto-first-sibling)
  ("e" hydra-org-goto-last-sibling)
  ;; level
  ("j" hydra-org-child-level)
  ("k" hydra-org-parent-level)
  ;; narrow
  ("o" nn-widen)
  ("i" nn-narrow)

  ("SPC" org-cycle)
  ("t" org-tidy)
  ("L" org-toggle-link-display)

  ("r" (lambda () (interactive)
         (helm-org-rifle-current-buffer)
         (call-interactively 'org-cycle)
         (call-interactively 'org-cycle)))
  ("v" avy-org-goto-heading-timer)
  ("s" avy-org-same-level)
  ("d" avy-org-child-level)
  ("f" avy-org-parent-level)
  ("S" (lambda () (interactive) (helm-org-in-buffer-headings) (org-cycle) (org-cycle)))

  ("1" (avy-org-goto-level 1))
  ("2" (avy-org-goto-level 2))
  ("3" (avy-org-goto-level 3))
  ("4" (avy-org-goto-level 4))
  ("5" (avy-org-goto-level 5)))
```
