### ISSUE TITLE
Support defhydra+

### ISSUE THREAD

**Issue by Kungsgeten** [jerrypnz/major-mode-hydra.el#18]
Hi! Thank you for this nice package!

Hydra now have a function called `defhydra+` which can be used to add heads to an already existing hydra. See: https://oremacs.com/2019/05/18/hydra-0.15.0/

Would it be possible for `pretty-hydra` to do something similar?

**Comment by jerrypnz** [comment]
Glad that you find it useful. I guess I can introduce a new `pretty-hydra-define+` macro that uses `defhydra+`.

**Comment by Kungsgeten** [comment]
I actually fiddled a bit with it today and made som changes to the code.
I'll see if I can submit a pull request.

**Comment by jerrypnz** [comment]
That sounds great! looking forward to your PR.

**Comment by Kungsgeten** [comment]
Added the PR! #19

**Comment by jerrypnz** [comment]
This is now supported via `pretty-hydra-define+`. Thanks @Kungsgeten for your patch.
