### ISSUE TITLE
Hydras and global key bindings 

### ISSUE THREAD

**Issue by Pfedj** [jerrypnz/major-mode-hydra.el#32]
Lets suppose I have a simple hydra for python-mode:

```
  (use-package major-mode-hydra
    :ensure t
    :bind
    ("M-SPC" . major-mode-hydra))


(major-mode-hydra-define python-mode (:quit-key ("<escape>" "q"))
  ("Eval"
   (("i" elpy-importmagic-fixup "Importmagic fixup")
    ("d" elpy-goto-definition "Goto definition"))))
```
1. I would like to have some key bindings that work in all modes (major or minor). 
2. And I would like hydra not to show hint for the key binding. 
For instance:
```
(global-set-key (kbd "M-<SPC> emr") 'restart-emacs)
```
There is a conflict with ```M-<SPC>``` of course. 
Can I do it with major-mode-hydra?

**Comment by jerrypnz** [comment]
> 1. I would like to have some key bindings that work in all modes (major or minor).

You can use `pretty-hydra` and bind it to a global key.

> 2. And I would like hydra not to show hint for the key binding.

Don't think you can hide the hint completely but you can [set an idle delay](https://github.com/abo-abo/hydra/wiki/internals#idle), e.g.

```elisp
(pretty-hydra-define test-hydra (:quit-key ("<escape>" "q") :idle 1.5)
  ("Eval"
   (("i" elpy-importmagic-fixup "Importmagic fixup")
    ("d" elpy-goto-definition "Goto definition"))))
```

**Comment by Pfedj** [comment]
> You can use pretty-hydra and bind it to a global key.

I have bind my pretty-hydra to the global key this way:
```
(defun Pfedj/hydra-test ()
  (interactive)
  (funcall
   (pretty-hydra-define test-hydra (:quit-key ("<escape>" "q"))
  ("Eval"
   (("i" elpy-importmagic-fixup "Importmagic fixup")
    ("d" elpy-goto-definition "Goto definition"))))))

(global-set-key (kbd "M-<SPC>") 'Pfedj/hydra-test)
```
I would like to add heads to an already existing ```test-hydra```:
```
(pretty-hydra-define+ test-hydra (:quit-key ("<escape>" "q") :idle 1.5)
  (;; these heads are added to the existing "Eval" column
   "Eval"
   (("r" transpose-frame "rotate")
    ("z" zone "zone out!"))
   ;; this is a new column, which gets added
   "Appearance"
   (("f" set-frame-font "font")
    ("t" load-theme "theme"))))
```
It doesn't work. How can I do it?

**Comment by jerrypnz** [comment]
It doesn't work because every time `Pfedj/hydra-test` is called, your hydra is re-defined with `pretty-hydra-define` which blows away the existing one. You don't really need that wrapper function, just bind the hydra body to a key:

```
(pretty-hydra-define test-hydra (:quit-key ("<escape>" "q"))
  ("Eval"
   (("i" elpy-importmagic-fixup "Importmagic fixup")
    ("d" elpy-goto-definition "Goto definition"))))

(global-set-key (kbd "M-<SPC>") 'test-hydra/body)
```

**Comment by Pfedj** [comment]
I have lost postfix ```/body``` when I try to bind hydra with ```global-set-key``` as you describe. So it works. Thank you for you clarification.
