### ISSUE TITLE
Calling a pretty hydra gives "wrong type argument" error

### ISSUE THREAD

**Issue by hjpotter92** [jerrypnz/major-mode-hydra.el#34]
I have defined the following pretty-hydra for omni-scratch package:

``` elisp
(use-package omni-scratch
  :custom
  (omni-scratch-pale-background nil)
  :pretty-hydra
  ((:color amaranth :quit-key "q" :title "Omni scratch buffer management")
   ("Omni Scratch"
    (("DEL" omni-scratch "omni-scratch")
     ("-" omni-scratch-major "major mode")
     ("_" omni-scratch-buffer "buffer")
     ("$" omni-scratch-goto-latest "goto latest")
     ("b" omni-scratch-buffers "buffers"))
    "Quit"
    (("q" nil "Quit hydra"))))
  :bind
  ("C-c $" . omni-scratch-hydra/body))
```

After trying to trigger the omni-scratch-hydra, it raises the following error:

```
apply: Wrong type argument: stringp, nil
```

Is the hydra definition wrong? Or is it some other issue?

**Comment by jerrypnz** [comment]
Hmm I couldn't reproduce it. I ran your code snippet and then pressed `C-c $`. The hydra showed up fine. Maybe try `M-x toggle-debug-on-error` and see where the error comes from.

**Comment by hjpotter92** [comment]
weird, I can reproduce the same error if I do `M-x omni-scratch-hydra/body`

**Comment by hjpotter92** [comment]
Closing the issue. I removed both packages, `omni-scratch` and `pretty-hydra`. On restarting emacs, things seem to be working smoothly.
