### ISSUE TITLE
missing one line with posframe

### ISSUE THREAD

**Issue by dlyr** [jerrypnz/major-mode-hydra.el#39]
Hi,
I'm trying to setup a specific pretty-hydra, but it miss the last line. I home my general configuration do not break somthing. I have 
```
(setq hydra-posframe-show-params '(:internal-border-width 1 :internal-border-color "#c6c6c6" :horizontal-scroll-bars 't :poshandler posframe-poshandler-frame-bottom-center)

(use-package pretty-hydra)

(use-package major-mode-hydra
  :ensure t
  :config
  (setq hydra-hint-display-type 'posframe)
  (setq major-mode-hydra-invisible-quit-key "q")
  :bind
  ("M-SPC" . major-mode-hydra))

(pretty-hydra-define test-hydra
  (:title "TEST" :color amaranth :quit-key "q")
   ("hello"
    (("cmp" nil "profile" )
     ("cmc" nil "cmake")
     ("cmb" nil "build")
   )))
```
When I call test-hydra/body only "profile" and "cmake" are shown in the posframe, not "build".
Any advice on where to search what i'm doing bad ? If I set  hydra-hint-display-type to 'lv everything looks fine.
++

**Comment by jerrypnz** [comment]
@dlyr Yeah I ran into the same issue as well but I'm pretty sure it's an issue in hydra-posframe or posframe. I ended up using my own fork with this hack: https://github.com/jerrypnz/hydra-posframe/commit/7a0506b0a6b75418d0c9c8927e022c2061b8881b

~~Can you check if you have the same issue without `hydra-posframe`?~~ Sorry I missed the part where you said it's fine with `lv`.

**Comment by jerrypnz** [comment]
It's a while back but I remember spending quite a bit of time on it. I think ultimately it's an issue with `posframe` or emacs child frame itself but I couldn't find the root cause of it. What I did was just adding an extra line to the end using `fit-frame-to-buffer`.

**Comment by dlyr** [comment]
fine for me (I wouldn't spend alot of time on it, when I see that, because it do not happend to all my posframe'd hydras, I had a dummy line at the end).
btw I do not use hydra-posframe but outof the box hydra's posframe support 
(see [this annoncment](https://github.com/abo-abo/hydra/blob/f27fce1b2f0a9162e159557bdeb2c0c94defb4d2/doc/Changelog.org#0150) or [in the code](https://github.com/abo-abo/hydra/blob/d3328cab67714fbc164781d7bbe0f9d150f2e9a3/hydra.el#L248))

**Comment by jerrypnz** [comment]
right i remember now. i tried it briefly but chose hydra-posframe because it's easier to customize.

**Comment by oracleyue** [comment]
@jerrypnz When we the built-in posframe support from `hydra`, that is `(setq hydra-hint-display-type 'posframe)`, the fix is as simple as adding one space at the end of your generated docstring: (the second is your original file `pretty-hydra.el`)

```
174c173
<          (format "\n%s\n "))))
---
>          (format "\n%s\n"))))
```
Adding one trailing space or not affects if the newline is respected.

You may quickly test the behavior in the example you provided in the issue:
```
(posframe-show "*test-posframe*" :string "\n foo \n bar \n foobar \n" :internal-border-width 1 :internal-border-color "red")
```
from https://github.com/jerrypnz/major-mode-hydra.el/issues/30#issuecomment-512978120.

PS: I didn't use `hydra-posframe`, which seems no longer necessary any more.
