### ISSUE TITLE
Differences between hydra and pretty-hydra?

### ISSUE THREAD

**Issue by twmr** [jerrypnz/major-mode-hydra.el#40]
The Readme of this project doesn't mention what the differences between hydra and pretty hydra are. 

According to the Commentary section in pretty-hydra.el
```el 
;; Provides a macro, `pretty-hydra-define', which defines a hydra with
;; column for each group of heads.
```
Is this everything? It would be nice, if this were mentioned in the Readme.

**Comment by jerrypnz** [comment]
Thanks for reporting the issue. I just pushed a commit adding more description to pretty-hydra. Hopefully that makes it a bit clearer.

**Comment by twmr** [comment]
@jerrypnz  Thx for improving the Readme!
