### ISSUE TITLE
how to add a head but hide it from the actual menu

### ISSUE THREAD

**Issue by hoebat** [jerrypnz/major-mode-hydra.el#45]
I'd like to define some mappings that do not show up on the hydra. Is there a way to do that?

Also, is there a way to (easily) define a blank line between the heads?

**Comment by jerrypnz** [comment]
> I'd like to define some mappings that do not show up on the hydra. Is there a way to do that?

You can set the hint to `nil`, e.g.

```lisp
(pretty-hydra-define jp-projects
  (:color teal :quit-key "q" :title (jp-projects--title))
  ("Current Project"
   (("f" counsel-projectile-find-file nil)
    ("b" counsel-projectile-switch-to-buffer "switch to buffer")
    ("d" counsel-projectile-find-dir "open directory")
    ("i" projectile-ibuffer "ibuffer")
    ("k" projectile-kill-buffers "kill buffers")
    ("I" projectile-invalidate-cache "invalidate cache"))
   "All Projects"
   (("p" jp-eyebrowse-switch-project "switch")
    ("r" jp-refresh-projectile-projects "refresh project list"))))
```

<img width="433" alt="image" src="https://user-images.githubusercontent.com/292028/103450439-4f9bd300-4d1b-11eb-8352-5ac917767417.png">

The "f" head does not show up but the keybinding still works.

> Also, is there a way to (easily) define a blank line between the heads?

I'm afraid there's currently no way to do that.

**Comment by hoebat** [comment]
@jerrypnz: thanks for that - and also the library. It really save me a lot of time with the configurations and messing about with hydra itself..
