### ISSUE TITLE
Minor mode support. 

### ISSUE THREAD

**Issue by WolfeCub** [jerrypnz/major-mode-hydra.el#8]
I know this goes against the package name but is there any reason you don't support minor modes?

I have similar functionality to this package in my dotfiles but when I switched over to this package I noticed it was missing minor mode support. 

Is there any chance of this being added?

Thanks!

**Comment by jerrypnz** [comment]
Sorry for the late response. Somehow I didn't receive notification for this.

That's an interesting idea. I never thought about it and don't have a use-case for it. I'm also not sure how it's gonna work because for a given buffer, multiple minor modes might be enabled. How should it decide which "minor mode hydra" to open when you invoke the command?

**Comment by WolfeCub** [comment]
I never really ran into that issue since I typically used it for modes that don't conflict but I suppose there could be a priority list in the config that determines the precedence of each mode.

**Comment by jerrypnz** [comment]
I don't know if I'd implement exactly what you want at this point. But I do have something in mind that will make it easier to achieve what you want. Basically I plan to introduce a new command where you can specify how you'd want to dispatch to different hydras.

**Comment by jerrypnz** [comment]
@WolfeCub On `develop` branch a new function was introduced: https://github.com/jerrypnz/major-mode-hydra.el/blob/develop/major-mode-hydra.el#L142

It should allow you to do something like this:

```elisp
(major-mode-hydra-bind foobar-mode "Eval"
  ("b" eval-buffer "buffer")
  ("e" eval-defun "defun")
  ("r" eval-region "region"))

(major-mode-hydra-bind foobar-mode "Test"
  ("t" ert "prompt")
  ("T" (ert t) "all")
  ("F" (ert :failed) "failed"))

(major-mode-hydra-bind foobar-mode "Doc"
  ("d" describe-foo-at-point "thing-at-pt")
  ("f" describe-function)
  ("v" describe-variable))

(defun call-foobar-hydra ()
  (interactive)
  (major-mode-hydra-dispatch 'foobar-mode))
```

You can create commands on top of that function to do your own dispatching.

**Comment by WolfeCub** [comment]
Great! Thanks for the follow up.
